config/routes.rb
Rails.application.routes.draw do
 
resources :sessions, only: [:new, :create, :destroy]  
	 get 'signup', to: 'users#new', as: 'signup'
	 get 'login', to: 'sessions#new', as: 'login'  
	 get 'logout', to: 'sessions#destroy', as: 'logout' 


 
  resources :users
 # get 'page/index'
  resources :books
resources :authors
resources :authordetails 
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'page#index'
  get 'page/index'  
 
end

app/models/author.rb
class Author < ApplicationRecord
#------------------------------
	
	has_many :addresses, as: :addressable, dependent: :destroy #succeessfull 

	has_one :authordetail, dependent: :destroy#succeessfull 

#------------------------------
	has_many :books, dependent: :destroy#succeessfull 
	validates_uniqueness_of :name
	accepts_nested_attributes_for :authordetail #THIS IS FOR THE NESTED FORM ==>>/home/admin2/Desktop/practice/scaffold/app/views/authors/
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :check_session
  

  # GET /authors  
  def index
    @authors = Author.order(:id)
  
   # @instance_variable = ModelClass.all
  end
  
  # GET /authors/1
  def show
    @ad = @author.authordetail

  end

  # GET /authors/new
  def new
    @author = Author.new
    @author.build_authordetail
    #@author.authordetail.build
  
  end

  # GET /authors/1/edit
  def edit  
    
  end

  # POST /authors
  def create
    @author = Author.new(author_params)
    @ad = Authordetail.new() 
    if @author.save
      redirect_to @author, notice: 'Author was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /authors/1
  def update
    if @author.update(author_params)
      redirect_to @author, notice: 'Author was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /authors/1
  def destroy
    @author.destroy
    redirect_to authors_url, notice: 'Author was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])  
    end

    # Only allow a trusted parameter "white list" through.
     def author_params
      params.require(:author).permit(:name, :address,:author_id, authordetail_attributes: [:id, :bio, :email, :mobile_No])
    end

    def check_session
      if session[:user_id]
         
      else  
          redirect_to  page_index_url, notice: 'login is required.' 
      end 
    end
end 

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %> 

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <!------------ nested form  SECOUDND FORM, SAME AS authordetails_form.html ----------------- -->
  <%= form.fields_for :authordetail do |ad| %>

   <h2>Personal Details</h2>

    <div class="field">
      <%= ad.label :bio %>
      <%= ad.text_area :bio %>
    </div>

    <div class="field">
      <%= ad.label :email %>
      <%= ad.text_field :email %>
    </div>

    <div class="field">
      <%= ad.label :mobile_No %>
      <%= ad.text_field :mobile_No %>
    </div>

  <% end %>

<!------------------TRY OVER --------------------------------------------------------------------->
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= form_with(model: @author,local: true) do |form| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>
  
  <!------------ nested form  SECOUDND FORM, SAME AS authordetails_form.html ----------------- -->
  <%= form.fields_for :authordetail do |ad| %>

   <h2>Personal Details</h2>

    <div class="field">
      <%= ad.label :bio %>
      <%= ad.text_area :bio %>
    </div>

    <div class="field">
      <%= ad.label :email %>
      <%= ad.text_field :email %>
    </div>

    <div class="field">
      <%= ad.label :mobile_No %>
      <%= ad.text_field :mobile_No %>
    </div>

  <% end %>

<!------------------TRY OVER ------------------->


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>



<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>created duration</th>
      <th>Practice </th>
      <th>njnnjnn</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.address %></td>
        
        <!--  HELPER METHOD PRACTICE-->
        <td><%= time_ago_in_words author.created_at %> </td>

            
        <td><%= truncate(author.address*10, length:10) %></td>
        
        <td> <%= number_to_human 5884 %></td>
        <!--  HELPER METHOD PRACTICE-->
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h2>
<%= link_to 'New Author', new_author_path %> ||
<%= link_to 'BACK ', books_path %> 
</h2>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @author.address %>
</p>


<p>
  <strong>Email address:</strong>
  <%= @ad.try(:email) %>
</p>


<p>
  <strong>Author Bio:</strong>
  <%= @ad.try(:bio) %>
</p>

<p>
  <strong>Mobile_No:</strong>
  <%= @ad.try(:mobile_No) %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %> |