config/routes.rb
Rails.application.routes.draw do
 
resources :sessions, only: [:new, :create, :destroy]  
	 get 'signup', to: 'users#new', as: 'signup'
	 get 'login', to: 'sessions#new', as: 'login'  
	 get 'logout', to: 'sessions#destroy', as: 'logout' 


 
  resources :users
 # get 'page/index'
  resources :books
resources :authors
resources :authordetails 
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'page#index'
  get 'page/index'  
 
end

app/models/book.rb
class Book < ApplicationRecord
  # delegate :example, :example2,  to: :user
#------------------------------
#has_many :users #processing
  belongs_to :user
# has_and_belongs_to_many :users# NOT WORKING s
#------------------------------ 

  belongs_to :author #succeessfull 

#create the initialize call back mehtod 
# its output is display on the terminal
		after_initialize do |book|
      puts "You have initialized an object!"
    end

  after_touch do |booke|
    	puts "You have touched an object"
  	end
 
  after_find do |book|
      puts "You have found an object!"
    end

 	after_destroy :log_destroy_action
 
	  def log_destroy_action
   		puts 'Article destroyed'
  	end
 	
 	before_save { |book| book.title = book.title.downcase }

	#attribute :slug, :string, default: str

  before_create :default_values


 		    def default_values
     			p "bhhbhbhj=--=-=-=-=-=-="
     			o = [('a'..'z'), ('A'..'Z')].map(&:to_a).flatten
     			str = (0..15).map { o[rand(o.length)] }.join
      			  
  			   if self.slug.nil? == true || self.slug.blank? == true || self.slug.class != Integer
      			self.slug = str
    	   	 end	
        end 

  after_update_commit :updated_book_saved_to_db


  	private
 			  def updated_book_saved_to_db
   			 	puts 'Book is updated to database'
 			  end

	after_save_commit :book_saved_to_db
 
 	  private
  			def book_saved_to_db
  			  puts 'book is saved to database'
  			end

	validates :title, presence: true, length: {minimum: 5,  maximum:20}
#	validates :author_name, presence: true, length: {minimum: 3,  maximum:20}
 
	validates_numericality_of :price, presence: true , :greater_than => 0, :less_than => 500

	validates :ISBN , presence:true, length: {minimum: 14, maximum: 15}

	
	validates :publishedyear, presence: true, format: {with: /(19|20)\d{2}/i }


	validates :publishedyear, :numericality => { greater_than_or_equal_to: 2010, less_than: 2020 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :check_session
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /bookstores
  # GET /bookstores.json
  def index
    @books= Book.all
  end

  # GET /bookstores/1
  # GET /bookstores/1.json
  def show  
    @books = Book.find(params[:id])
    @authorname= @book.author

  end

  # GET /bookstores/new

  def new
    @book = Book.new

  end

  # GET /bookstores/1/edit
  def edit

  end

  # POST /bookstores
  # POST /bookstores.json
  def create


    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice:  'Book was successfully created.' }
        puts @book.as_json 
        format.json { render :show, status: :created, location: @book }
      else
        
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /bookstores/1
  # PATCH/PUT /bookstores/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookstores/1
  # DELETE /bookstores/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to book_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
    # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def book_params
    params.require(:book).permit(:title, :price, :language, :publishedyear, :ISBN, :author_id, :name, :user_id)
  end

  def check_session
    if session[:user_id]
       
    else  
        redirect_to  page_index_url, notice: 'login is required.' 
    end 
  end
    
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>

  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  
  <div class="field">
    <%= form.label :select_author%>
    <%= form.collection_select :author_id, Author.order(:name),:id,:name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>


  <div class="field">
    <%= form.label :select_user%>
    <%= form.collection_select :user_id, User.order(:username),:id,:username %>
  </div>    

    
 <div class="field">
    <%= form.label :language %>
  
    <%= form.select :language, ["HINDI","ENGLISH","GUJRATI"]%>
  </div>  
  


  <div class="field">
    <%= form.label :publishedyear %>
    <%= form.number_field :publishedyear %>
  </div>

  <div class="field">
    <%= form.label :ISBN %>
    <%= form.text_field :ISBN %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Bookstore</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>
	

app/views/books/index.html.erb
<font size="18"> <p id="notice"><%= notice %></p> </font> 

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author_name</th>
      <th>language</th>
      <th>Price</th>
      <th>Publishedyear</th>
      <th>Isbn</th>
      <th>slug</th>
      <th colspan="3">Operation</th>
    </tr>
  </thead>
  
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author.name %></td>
        <td><%= book.language %></td>
        <td><%= book.price %></td>  
        <td><%= book.publishedyear %></td>
        <td><%= book.ISBN %></td>
        <td><%= book.slug%></td>  
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h2>
<%= link_to 'New Book', new_book_path %> ||
<%= link_to 'LIST OF AUTHORS ', authors_path %>
</h2>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<font size="18"><p id="notice"><%= notice %></p> </font>  



<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @authorname.name %>
</p>

<p>
  <strong>Language:</strong>
  <%= @book.language %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>


<p>
  <strong>Slug:</strong>
  <%= @book.slug %>
</p>

<p>
  <strong>Publishedyear:</strong>
  <%= @book.publishedyear %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.ISBN %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>