config/routes.rb
Rails.application.routes.draw do
 
resources :sessions, only: [:new, :create, :destroy]  
	 get 'signup', to: 'users#new', as: 'signup'
	 get 'login', to: 'sessions#new', as: 'login'  
	 get 'logout', to: 'sessions#destroy', as: 'logout' 


 
  resources :users
 # get 'page/index'
  resources :books
resources :authors
resources :authordetails 
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'page#index'
  get 'page/index'  
 
end

app/models/authordetail.rb
class Authordetail < ApplicationRecord
#-----------------------------
	belongs_to :author#succeessfull                                           
#------------------------------
validates :email,  
            presence: true,  
            uniqueness: true,  
            format: {  
              with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i  
            }

validates :bio, presence: true
validates :mobile_No, presence: true

end

app/controllers/authordetails_controller.rb
class AuthordetailsController < ApplicationController
  before_action :set_authordetail, only: [:show, :edit, :update, :destroy]
  before_action :check_session


  # GET /authordetails
  def index
    @authordetails = Authordetail.includes(:author)
    #@authordetailssss = Authordetail.joins(:author).where("author_id = ?", 6)

  end
  # GET /authordetails/1
  def show

  end

  # GET /authordetails/new
  def new 
    @authordetail = Authordetail.new

  end

  # GET /authordetails/1/edit
  def edit
    @author= @authordetail.author.name
 puts "-------------------------------------------------------"
    puts @author
 puts "-------------------------------------------------------"
  
  end


  # POST /authordetails
  def create
    @authordetail = Authordetail.new(authordetail_params)

    if @authordetail.save
      redirect_to @authordetail, notice: 'Authordetail was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /authordetails/1
  def update
    @author= @authordetail.author

    if @authordetail.update(authordetail_params)
      #redirect_to @authordetail, notice: 'Authordetail was successfully updated.'

      redirect_to author_path(@author)
    else
      render :edit
    end
  end

  # DELETE /authordetails/1
  def destroy
    @authordetail.destroy
    redirect_to authordetails_url, notice: 'Authordetail was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_authordetail
      @authordetail = Authordetail.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def authordetail_params
      params.require(:authordetail).permit(:name ,:bio, :email, :mobile_No, :author_id)
    end

    def check_session
      if session[:user_id]
         
      else  
          redirect_to  page_index_url, notice: 'login is required.' 
      end 
    end


end

app/helpers/authordetails_helper.rb
module AuthordetailsHelper
end

app/views/authordetails/_form.html.erb
<%= form_with(model: authordetail, local: true) do |form| %>
  <% if authordetail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(authordetail.errors.count, "error") %> prohibited this authordetail from being saved:</h2>

      <ul>
        <% authordetail.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :author_id %>
    <%= form.collection_select :author_id, Author.order(:name),:id, :name %>
  </div>


  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :mobile_No %>
    <%= form.text_field :mobile_No %>
  </div>

 
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authordetails/edit.html.erb
<h1>Editing Authordetail</h1>



<%= form_with(model: @authordetail, local: true) do |form| %>
  <% if @authordetail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authordetail.errors.count, "error") %> prohibited this authordetail from being saved:</h2>

      <ul>
        <% @authordetail.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, :value=> @author %> 

  </div>


  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :mobile_No %>
    <%= form.text_field :mobile_No %>
  </div>

 
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', @authordetail %> |
<%= link_to 'Back', authordetails_path %>

app/views/authordetails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authordetails</h1>

<table>
  <thead>
    <tr>
      <th>Author Name</th>
      <th>Bio</th>
      <th>Email</th>
      <th>Mobile no</th>
       <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authordetails.each do |authordetail| %>
      <tr>
        <td><%= authordetail.author.name %></td>
        <td><%= authordetail.bio %></td>
        <td><%= authordetail.email %></td>
        <td><%= authordetail.mobile_No %></td>
        <td><%= link_to 'Show', authordetail %></td>
        <td><%= link_to 'Edit', edit_authordetail_path(authordetail) %></td>
        <td><%= link_to 'Destroy', authordetail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Authordetail', new_authordetail_path %>

app/views/authordetails/new.html.erb
<h1>New Authordetail</h1>

<%= render 'form', authordetail: @authordetail %>

<%= link_to 'Back', authordetails_path %>

app/views/authordetails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @authordetail.author.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @authordetail.bio %>
</p>

<p>
  <strong>Email:</strong>
  <%= @authordetail.email %>
</p>

<p>
  <strong>Mobile no:</strong>
  <%= @authordetail.mobile_No %>
</p>



<%= link_to 'Edit', edit_authordetail_path(@authordetail) %> |
<%= link_to 'Back', authordetails_path %>